"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useDeferredValue, useEffect, useMemo, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Icon } from "@/components/admin/icons";
import { useAction } from "@/components/admin/useAction";
import { Button, Checkbox, Field, Input, Notice, Panel, Select, Textarea, labelClass } from "@/components/admin/ui";
import { addDays, num } from "@/lib/admin/format";
import { computeTotals, type TaxInput } from "@/lib/admin/invoice-math";
import {
  CREDIT_REASONS,
  CURRENCIES,
  FREQUENCIES,
  addPeriods,
  blankItem,
  brandingFrom,
  businessFrom,
  cataloguePrice,
  clientAddress,
  docMoney,
  lineTax,
  type CatalogueItem,
  type ClientOption,
  type CreditReason,
  type DocStatus,
  type DocumentData,
  type DocumentInput,
  type EditorDoc,
  type EditorItem,
  type Frequency,
  type InvoiceSettings,
  type LeadOption,
  type ScheduleDraft,
  type ScheduleInput,
  type TaxRate,
} from "@/lib/admin/invoice-types";
import { saveDocument, saveScheduleTemplate } from "@/app/admin/actions/invoices";
import InvoiceDocument from "./InvoiceDocument";
import ScaledSheet from "./ScaledSheet";
import { CataloguePicker, LineTaxes } from "./LineExtras";
import { linkButton } from "./parts";

/**
 * Create and edit invoices, quotes and recurring templates.
 *
 * Form on the left, the real document on the right from `lg` up — sticky and
 * scaled to fit the column and the viewport. Below `lg` a sticky
 * "Total · Preview" bar opens the paper full screen. Totals come from
 * computeTotals(), the same maths the database runs on save.
 */

type Item = EditorItem & { key: string; open: boolean };

type Props = {
  mode: "create" | "edit" | "schedule";
  initial: EditorDoc;
  /** The saved row being edited (edit mode). */
  invoice?: {
    id: string;
    number: string | null;
    status: DocStatus;
    amount_paid: number;
    paid_at: string | null;
    source_quote_number?: string | null;
    /** Generated by a schedule already — no "Make recurring" on it. */
    scheduled?: boolean;
  } | null;
  /** The schedule whose template is being edited (schedule mode). */
  schedule?: { id: string; draft: ScheduleDraft } | null;
  startRecurring?: boolean;
  settings: InvoiceSettings;
  clients: ClientOption[];
  leads: LeadOption[];
  owners: { id: string; name: string }[];
  viewer: { id: string; admin: boolean; canClients: boolean };
  today: string;
  /** The workspace's tax rates (0032) — what a line can carry. */
  taxRates?: TaxRate[];
  /** Saved products and services (0034). */
  catalogue?: CatalogueItem[];
  /** The last rate used per currency, to pre-fill a foreign document's. */
  lastRates?: Record<string, number>;
  /** A credit note: the invoice it credits and what's left to credit on it. */
  creditFor?: { id: string; number: string | null; currency: string; room: number } | null;
};

const DUE_TERMS = [0, 7, 14, 30, 45];
const VALID_TERMS = [7, 14, 30, 60];

const daysBetween = (from: string, to: string) => Math.round((Date.parse(to) - Date.parse(from)) / 86_400_000);
const isDay = (v: string) => /^\d{4}-\d{2}-\d{2}$/.test(v);

export default function InvoiceEditor({
  mode,
  initial,
  invoice = null,
  schedule = null,
  startRecurring = false,
  settings,
  clients,
  leads,
  owners,
  viewer,
  today,
  taxRates = [],
  catalogue = [],
  lastRates = {},
  creditFor = null,
}: Props) {
  const router = useRouter();
  const { run, pending, toast } = useAction();

  const [doc, setDoc] = useState<EditorDoc>(initial);
  const [items, setItems] = useState<Item[]>(() =>
    initial.items.map((it, i) => ({ ...it, key: `i${i}`, open: !!it.details })),
  );
  const [seq, setSeq] = useState(0);
  const [saveClient, setSaveClient] = useState(false);
  const [sheet, setSheet] = useState(false);

  const [recurring, setRecurring] = useState(mode === "schedule" || startRecurring);
  const [sched, setSched] = useState<ScheduleDraft>(
    schedule?.draft ?? {
      name: "",
      is_retainer: false,
      frequency: "monthly",
      interval_count: "1",
      anchor_date: initial.issue_date,
      next_run_on: "",
      ends_on: "",
      max_occurrences: "",
      auto_issue: false,
      active: true,
    },
  );
  const [nextTouched, setNextTouched] = useState(mode === "schedule");

  // After a save the server sends the stored version back (router.refresh) —
  // adopt it, so a new client link or rounded figure isn't overwritten by the
  // next save. A create never re-seeds: it moves to the edit page instead.
  const [seed, setSeed] = useState(initial);
  if (mode !== "create" && seed !== initial) {
    setSeed(initial);
    setDoc(initial);
    setItems(initial.items.map((it, i) => ({ ...it, key: `i${i}`, open: !!it.details })));
    if (schedule) setSched(schedule.draft);
  }

  const quote = doc.kind === "quote";
  const credit = doc.kind === "credit_note";
  const foreign = doc.currency !== "LKR";
  const activeRates = taxRates.filter((r) => r.active);
  const defaultTaxes = activeRates.filter((r) => r.is_default).map(lineTax);
  const paid = num(invoice?.amount_paid);
  const locked = paid > 0;
  const status: DocStatus = invoice?.status ?? "draft";
  const isDraft = status === "draft";
  const id = invoice?.id;

  const totals = useMemo(
    () =>
      computeTotals({
        items,
        discount_type: doc.discount_type,
        discount_value: doc.discount_value,
        tax_rate: doc.tax_rate,
        tax_label: doc.tax_label,
        prices_include_tax: doc.prices_include_tax,
      }),
    [items, doc.discount_type, doc.discount_value, doc.tax_rate, doc.tax_label, doc.prices_include_tax],
  );
  const belowPaid = locked && totals.total < paid;
  const overCredit = credit && creditFor ? totals.total > creditFor.room + 0.004 : false;

  const set = <K extends keyof EditorDoc>(key: K, value: EditorDoc[K]) => setDoc((d) => ({ ...d, [key]: value }));

  /* ── dates ── */
  const setIssueDate = (value: string) =>
    setDoc((d) => {
      if (!isDay(value) || !isDay(d.issue_date)) return { ...d, issue_date: value };
      // Keep the payment window when the issue date moves.
      const shift = (to: string) => (isDay(to) ? addDays(value, daysBetween(d.issue_date, to)) : to);
      return { ...d, issue_date: value, due_date: shift(d.due_date), valid_until: shift(d.valid_until) };
    });

  /* ── bill to ── */
  const fromClient = (c: ClientOption) => ({
    client_id: c.id,
    bill_to_name: c.name,
    bill_to_company: c.company ?? "",
    bill_to_email: c.email ?? "",
    bill_to_phone: c.phone ?? "",
    bill_to_address: clientAddress(c),
    bill_to_tax_id: c.tax_id ?? "",
  });

  /* ── currency ── */
  const setCurrency = (currency: string) =>
    setDoc((d) => ({
      ...d,
      currency,
      // A rupee document carries no rate; a foreign one starts from the last rate used.
      exchange_rate: currency === "LKR" ? "" : d.exchange_rate || (lastRates[currency] ? String(lastRates[currency]) : ""),
    }));

  const pickClient = (clientId: string) => {
    const c = clients.find((x) => x.id === clientId);
    setDoc((d) => (c ? { ...d, ...fromClient(c) } : { ...d, client_id: "" }));
  };

  const pickLead = (leadId: string) => {
    const lead = leads.find((l) => l.id === leadId);
    setDoc((d) => {
      const next = { ...d, lead_id: leadId };
      if (!lead || d.client_id) return next;
      const c = lead.client_id ? clients.find((x) => x.id === lead.client_id) : null;
      if (c) return { ...next, ...fromClient(c) };
      if (d.bill_to_name.trim()) return next;
      return {
        ...next,
        bill_to_name: lead.name,
        bill_to_company: lead.company ?? "",
        bill_to_email: lead.email ?? "",
        bill_to_phone: lead.phone ?? "",
      };
    });
  };

  /* ── line items ── */
  const updateItem = (key: string, patch: Partial<Item>) =>
    setItems((list) => list.map((it) => (it.key === key ? { ...it, ...patch } : it)));
  // A new line carries the taxes the lines above use (or the workspace defaults).
  const taxesForNewLine = (list: Item[]): TaxInput[] => {
    const last = list[list.length - 1];
    return last && last.taxes.length ? last.taxes : defaultTaxes;
  };
  const addItem = () => {
    setItems((list) => [...list, { ...blankItem(taxesForNewLine(list)), key: `n${seq}`, open: false }]);
    setSeq(seq + 1);
  };
  const removeItem = (key: string) =>
    setItems((list) =>
      list.length > 1
        ? list.filter((it) => it.key !== key)
        : list.map((it) => ({ ...it, ...blankItem(defaultTaxes), open: false })),
    );
  const fromCatalogue = (key: string, entry: CatalogueItem) => {
    const price = cataloguePrice(entry, doc.currency);
    const taxes = (entry.tax_rate_ids ?? [])
      .map((rid) => taxRates.find((r) => r.id === rid))
      .filter((r): r is TaxRate => !!r)
      .map(lineTax);
    updateItem(key, {
      description: entry.name,
      details: entry.details ?? "",
      open: !!entry.details,
      unit_price: price == null ? "" : String(price),
      taxes,
    });
  };
  const moveItem = (key: string, by: -1 | 1) =>
    setItems((list) => {
      const from = list.findIndex((it) => it.key === key);
      const to = from + by;
      if (from < 0 || to < 0 || to >= list.length) return list;
      const next = [...list];
      [next[from], next[to]] = [next[to], next[from]];
      return next;
    });

  /* ── schedule ── */
  const every = Math.max(1, Math.floor(num(sched.interval_count, 1)));
  const anchor = mode === "schedule" ? sched.anchor_date : doc.issue_date;
  const nextRun = nextTouched ? sched.next_run_on : isDay(anchor) ? addPeriods(anchor, sched.frequency, every) : "";
  const scheduleName = sched.name || [doc.bill_to_company || doc.bill_to_name, doc.subject].filter((x) => x.trim()).join(" · ");

  const scheduleInput = (): ScheduleInput => ({
    name: scheduleName,
    is_retainer: sched.is_retainer,
    frequency: sched.frequency,
    interval_count: every,
    anchor_date: anchor,
    next_run_on: nextRun,
    ends_on: sched.ends_on || null,
    max_occurrences: num(sched.max_occurrences) > 0 ? Math.floor(num(sched.max_occurrences)) : null,
    auto_issue: viewer.admin && sched.auto_issue,
    active: sched.active,
  });

  /* ── save ── */
  const toInput = (): DocumentInput => ({
    id,
    kind: doc.kind,
    client_id: doc.client_id || null,
    lead_id: doc.lead_id || null,
    owner_id: doc.owner_id || null,
    bill_to_name: doc.bill_to_name,
    bill_to_company: doc.bill_to_company || null,
    bill_to_email: doc.bill_to_email || null,
    bill_to_phone: doc.bill_to_phone || null,
    bill_to_address: doc.bill_to_address || null,
    subject: doc.subject || null,
    issue_date: mode === "schedule" ? nextRun || doc.issue_date : doc.issue_date,
    due_date: quote ? null : doc.due_date || null,
    valid_until: quote ? doc.valid_until || null : null,
    currency: doc.currency,
    discount_type: doc.discount_type,
    discount_value: num(doc.discount_value),
    tax_label: doc.tax_label,
    // Lines carry the taxes now (0032); the document-wide rate stays at zero.
    tax_rate: 0,
    notes: doc.notes || null,
    terms: doc.terms || null,
    payment_details: doc.payment_details || null,
    exchange_rate: foreign && num(doc.exchange_rate) > 0 ? num(doc.exchange_rate) : null,
    prices_include_tax: doc.prices_include_tax,
    supply_date: doc.supply_date || null,
    bill_to_tax_id: doc.bill_to_tax_id.trim() || null,
    credited_invoice_id: credit ? doc.credited_invoice_id || null : null,
    credit_reason: credit ? (doc.credit_reason || "other") : null,
    items: items.map((it) => ({
      description: it.description,
      details: it.details || null,
      quantity: num(it.quantity),
      unit_price: num(it.unit_price),
      taxes: it.taxes,
    })),
  });

  const save = (issue: boolean) => {
    if (mode === "schedule" && schedule) {
      run(() => saveScheduleTemplate(schedule.id, toInput(), scheduleInput()));
      return;
    }
    const withSchedule = recurring && !quote && !credit;
    run(() => saveDocument(toInput(), { issue, recurring: withSchedule ? scheduleInput() : null, saveClient: saveClient && !locked && !credit }), {
      onDone: (r) => {
        if (!r.id) return;
        if (r.ok && (issue || !isDraft)) {
          router.push(`/admin/invoices/${r.id}?just=${issue ? "issued" : "saved"}`);
          return;
        }
        if (!invoice) {
          // The draft exists now — keep working on it at its own URL, never on a twin.
          const just = !r.ok ? "partial" : withSchedule ? "scheduled" : "draft";
          router.replace(`/admin/invoices/${r.id}/edit?just=${just}`);
          return;
        }
        setSaveClient(false);
        if (r.ok && withSchedule) setRecurring(false);
      },
    });
  };

  /* ── preview ── */
  const dueDays = settings.default_due_days;
  const previewItems = useMemo(
    () =>
      items.map((it) => ({
        description: it.description,
        details: it.details || null,
        quantity: it.quantity,
        unit_price: it.unit_price,
        taxes: it.taxes,
      })),
    [items],
  );
  const preview = useMemo<DocumentData>(() => ({
    kind: doc.kind,
    number: invoice?.number ?? null,
    status,
    bill_to_name: doc.bill_to_name,
    bill_to_company: doc.bill_to_company || null,
    bill_to_email: doc.bill_to_email || null,
    bill_to_phone: doc.bill_to_phone || null,
    bill_to_address: doc.bill_to_address || null,
    subject: doc.subject || null,
    issue_date: mode === "schedule" ? nextRun || today : isDay(doc.issue_date) ? doc.issue_date : today,
    due_date: quote || credit ? null : mode === "schedule" ? addDays(nextRun || today, dueDays) : isDay(doc.due_date) ? doc.due_date : null,
    valid_until: quote && isDay(doc.valid_until) ? doc.valid_until : null,
    currency: doc.currency,
    discount_type: doc.discount_type,
    discount_value: doc.discount_value,
    tax_label: doc.tax_label,
    tax_rate: doc.tax_rate,
    notes: doc.notes || null,
    terms: doc.terms || null,
    payment_details: doc.payment_details || null,
    items: previewItems,
    amount_paid: paid,
    paid_at: invoice?.paid_at ?? null,
    exchange_rate: foreign && num(doc.exchange_rate) > 0 ? num(doc.exchange_rate) : null,
    prices_include_tax: doc.prices_include_tax,
    supply_date: isDay(doc.supply_date) ? doc.supply_date : null,
    bill_to_tax_id: doc.bill_to_tax_id || null,
    credited_number: creditFor?.number ?? null,
    credit_reason: credit ? (doc.credit_reason || null) : null,
  }), [doc, quote, credit, foreign, status, mode, nextRun, today, dueDays, previewItems, paid, invoice?.number, invoice?.paid_at, creditFor?.number]);
  // Typing stays instant; the paper catches up a frame later on slow devices.
  const shown = useDeferredValue(preview);
  const business = businessFrom(settings);
  const branding = brandingFrom(settings);
  const taxInvoice = !!settings.tax_registered;
  const totalText = docMoney(totals.total, doc.currency);

  useEffect(() => {
    if (!sheet) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setSheet(false);
    };
    document.addEventListener("keydown", onKey);
    return () => {
      document.body.style.overflow = prev;
      document.removeEventListener("keydown", onKey);
    };
  }, [sheet]);

  const hasOwner = owners.some((o) => o.id === doc.owner_id);
  const hasClient = clients.some((c) => c.id === doc.client_id);
  const hasLead = leads.some((l) => l.id === doc.lead_id);
  const cancelHref =
    mode === "schedule"
      ? "/admin/invoices/recurring"
      : id
        ? `/admin/invoices/${id}`
        : creditFor
          ? `/admin/invoices/${creditFor.id}`
          : "/admin/invoices";

  return (
    <>
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)] 2xl:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]">
        <div className="@container min-w-0 space-y-4">
          {/* Context banners */}
          {mode === "edit" && !isDraft && !quote && (
            <Notice tone="info" title={`Issued as ${invoice?.number ?? "—"} · ${docMoney(paid, doc.currency)} received`}>
              Edits update the issued invoice.{" "}
              {locked
                ? "Currency and client are locked now that a payment is recorded, and the total can't drop below what's been paid."
                : "Once a payment is recorded, currency and client lock."}
            </Notice>
          )}
          {mode === "edit" && quote && !isDraft && (
            <Notice tone="info" title={`Quote ${invoice?.number ?? ""} is ${status === "accepted" ? "accepted" : "out with the client"}`}>
              Changes show on the next print — let the client know if the price moved.
            </Notice>
          )}
          {invoice?.source_quote_number && isDraft && (
            <Notice tone="info" title={`Made from quote ${invoice.source_quote_number}`}>
              Check the lines and dates, then issue it.
            </Notice>
          )}
          {credit && creditFor && (
            <Notice tone="info" title={`Credit note for ${creditFor.number ?? "an invoice"}`}>
              Issuing it takes its total off the invoice — up to {docMoney(creditFor.room, creditFor.currency)} is left to
              credit. If the client has already paid, record the refund on the invoice afterwards.
            </Notice>
          )}
          {mode === "schedule" && (
            <Notice tone="info" title="Editing a recurring template">
              Each run copies these lines into a new invoice dated on the run day, due {settings.default_due_days} days later.
              Invoices already generated don&apos;t change.
            </Notice>
          )}

          {/* Document */}
          <Panel title={mode === "schedule" ? "Template" : credit ? "Credit note" : quote ? "Quote" : "Invoice"} hint={headHint(mode, quote, credit)}>
            <div className="space-y-3">
              {mode === "create" && !credit && (
                <div className="grid grid-cols-2 gap-2" role="radiogroup" aria-label="Document type">
                  {(["invoice", "quote"] as const).map((k) => (
                    <button
                      key={k}
                      type="button"
                      role="radio"
                      aria-checked={doc.kind === k}
                      onClick={() => set("kind", k)}
                      className={`min-h-9 border px-3 py-2 text-[12.5px] font-medium transition-colors duration-300 ${doc.kind === k ? "border-terra/50 bg-terra/15 text-terra-bright" : "border-cream/12 bg-cream/[0.03] text-sand hover:text-cream"}`}
                    >
                      {k === "invoice" ? "Invoice" : "Quote"}
                    </button>
                  ))}
                </div>
              )}

              <div className="grid grid-cols-1 gap-3 @md:grid-cols-2">
                {mode !== "schedule" && (
                  <Field label="Number">
                    <Input value={invoice?.number ?? "Assigned on issue"} readOnly disabled />
                  </Field>
                )}
                {owners.length > 0 && (
                  <Field label="Owner" hint="Who follows it up. Used by the Mine filter.">
                    <Select value={doc.owner_id} onChange={(e) => set("owner_id", e.target.value)}>
                      {!hasOwner && (
                        <option value={doc.owner_id} className="bg-ink text-cream">
                          {doc.owner_id ? "Current owner" : "No owner"}
                        </option>
                      )}
                      {owners.map((o) => (
                        <option key={o.id} value={o.id} className="bg-ink text-cream">
                          {o.id === viewer.id ? `${o.name} (you)` : o.name}
                        </option>
                      ))}
                    </Select>
                  </Field>
                )}
                {mode !== "schedule" && (
                  <Field label="Issue date">
                    <Input type="date" value={doc.issue_date} onChange={(e) => setIssueDate(e.target.value)} required />
                  </Field>
                )}
                <Field
                  label="Currency"
                  hint={credit ? "The invoice's currency." : locked ? "Locked — a payment is recorded." : undefined}
                >
                  <Select value={doc.currency} disabled={locked || credit} onChange={(e) => setCurrency(e.target.value)}>
                    {(CURRENCIES.includes(doc.currency) ? CURRENCIES : [doc.currency, ...CURRENCIES]).map((c) => (
                      <option key={c} value={c} className="bg-ink text-cream">
                        {c}
                      </option>
                    ))}
                  </Select>
                </Field>
                {foreign && (
                  <Field
                    label={`Rate · LKR per 1 ${doc.currency}`}
                    hint={taxInvoice ? "The Central Bank's selling rate on the invoice date." : "Counts it in rupees in the totals and reports."}
                  >
                    <Input
                      type="number"
                      inputMode="decimal"
                      min="0"
                      step="0.0001"
                      value={doc.exchange_rate}
                      onChange={(e) => set("exchange_rate", e.target.value)}
                      placeholder={lastRates[doc.currency] ? String(lastRates[doc.currency]) : "e.g. 299.50"}
                      className="font-mono tabular-nums"
                    />
                  </Field>
                )}
                {credit && (
                  <Field label="Reason">
                    <Select value={doc.credit_reason || "other"} onChange={(e) => set("credit_reason", e.target.value as CreditReason)}>
                      {doc.credit_reason === "write_off" && (
                        <option value="write_off" className="bg-ink text-cream">
                          Bad debt written off
                        </option>
                      )}
                      {CREDIT_REASONS.map((r) => (
                        <option key={r.value} value={r.value} className="bg-ink text-cream">
                          {r.label}
                        </option>
                      ))}
                    </Select>
                  </Field>
                )}
                {taxInvoice && !quote && mode !== "schedule" && (
                  <Field label="Date of supply" hint="Leave empty when it's the issue date.">
                    <Input type="date" value={doc.supply_date} onChange={(e) => set("supply_date", e.target.value)} />
                  </Field>
                )}
              </div>

              {mode !== "schedule" && !credit && (
                <div>
                  <span className={labelClass}>{quote ? "Valid until" : "Due date"}</span>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <div className="min-w-[150px] flex-1 @md:max-w-[190px]">
                      <Input
                        type="date"
                        value={quote ? doc.valid_until : doc.due_date}
                        min={doc.issue_date}
                        onChange={(e) => set(quote ? "valid_until" : "due_date", e.target.value)}
                        aria-label={quote ? "Valid until" : "Due date"}
                      />
                    </div>
                    {(quote ? VALID_TERMS : DUE_TERMS).map((days) => {
                      const target = isDay(doc.issue_date) ? addDays(doc.issue_date, days) : "";
                      const current = (quote ? doc.valid_until : doc.due_date) === target;
                      return (
                        <button
                          key={days}
                          type="button"
                          onClick={() => target && set(quote ? "valid_until" : "due_date", target)}
                          className={`min-h-9 border px-2.5 text-[11.5px] transition-colors duration-300 ${current ? "border-terra/50 bg-terra/15 text-terra-bright" : "border-cream/12 bg-cream/[0.03] text-sand hover:text-cream"}`}
                        >
                          {days === 0 ? "On receipt" : `${days} days`}
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}

              <Field label="Subject" hint="One line on the paper — the project or period it covers.">
                <Input
                  value={doc.subject}
                  onChange={(e) => set("subject", e.target.value)}
                  placeholder={quote ? "Website redesign — phase 2" : "Monthly retainer — October"}
                />
              </Field>
            </div>
          </Panel>

          {/* Bill to */}
          <Panel title={quote ? "Prepared for" : "Bill to"} hint="Pick a client to fill this in, or type it.">
            <div className="space-y-3">
              <div className="grid grid-cols-1 gap-3 @md:grid-cols-2">
                <Field
                  label="Client"
                  hint={credit ? "The invoice's client." : locked ? "Locked — a payment is recorded." : clients.length === 0 ? "No clients to pick from yet." : undefined}
                >
                  <Select value={doc.client_id} disabled={locked || credit} onChange={(e) => pickClient(e.target.value)}>
                    <option value="" className="bg-ink text-cream">
                      — Not linked —
                    </option>
                    {doc.client_id && !hasClient && (
                      <option value={doc.client_id} className="bg-ink text-cream">
                        Linked client
                      </option>
                    )}
                    {clients.map((c) => (
                      <option key={c.id} value={c.id} className="bg-ink text-cream">
                        {c.company && c.company !== c.name ? `${c.name} · ${c.company}` : c.name}
                      </option>
                    ))}
                  </Select>
                </Field>
                {(leads.length > 0 || doc.lead_id) && (
                  <Field label="Linked lead" hint="Optional — ties it to the CRM card.">
                    <Select value={doc.lead_id} onChange={(e) => pickLead(e.target.value)}>
                      <option value="" className="bg-ink text-cream">
                        — None —
                      </option>
                      {doc.lead_id && !hasLead && (
                        <option value={doc.lead_id} className="bg-ink text-cream">
                          Linked lead
                        </option>
                      )}
                      {leads.map((l) => (
                        <option key={l.id} value={l.id} className="bg-ink text-cream">
                          {l.company ? `${l.name} · ${l.company}` : l.name}
                        </option>
                      ))}
                    </Select>
                  </Field>
                )}
              </div>

              <div className="grid grid-cols-1 gap-3 @md:grid-cols-2">
                <Field label="Name">
                  <Input value={doc.bill_to_name} onChange={(e) => set("bill_to_name", e.target.value)} placeholder="Nadeesha Perera" required />
                </Field>
                <Field label="Company">
                  <Input value={doc.bill_to_company} onChange={(e) => set("bill_to_company", e.target.value)} placeholder="Kite Interiors (Pvt) Ltd" />
                </Field>
                <Field label="Email">
                  <Input type="email" value={doc.bill_to_email} onChange={(e) => set("bill_to_email", e.target.value)} />
                </Field>
                <Field label="Phone">
                  <Input type="tel" value={doc.bill_to_phone} onChange={(e) => set("bill_to_phone", e.target.value)} />
                </Field>
                {(taxInvoice || doc.bill_to_tax_id) && (
                  <Field label="Their TIN / VAT no." hint="Prints on tax invoices when the client is VAT-registered.">
                    <Input value={doc.bill_to_tax_id} onChange={(e) => set("bill_to_tax_id", e.target.value)} maxLength={40} />
                  </Field>
                )}
              </div>
              <Field label="Address">
                <Textarea rows={3} value={doc.bill_to_address} onChange={(e) => set("bill_to_address", e.target.value)} />
              </Field>

              {/* Not once a payment locks the client — the save would be refused. */}
              {mode !== "schedule" && !credit && !doc.client_id && !locked && viewer.canClients && (
                <Checkbox
                  checked={saveClient}
                  onChange={(e) => setSaveClient(e.target.checked)}
                  label="Save to Clients"
                  hint="Adds these details to the client directory and links this document to it."
                />
              )}
            </div>
          </Panel>

          {/* Line items */}
          <Panel
            title="Line items"
            hint="Use the arrows to reorder."
            right={<span className="font-mono text-[11px] text-sand tabular-nums">{items.length} line{items.length === 1 ? "" : "s"}</span>}
          >
            <ol className="space-y-2.5">
              {items.map((it, i) => (
                <li key={it.key} className="border border-cream/[0.08] bg-ink/40 p-3">
                  <div className="flex items-start gap-2.5">
                    <span className="mt-2.5 w-5 shrink-0 font-mono text-[10px] text-sand tabular-nums">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <div className="@container min-w-0 flex-1 space-y-2">
                      <Input
                        value={it.description}
                        onChange={(e) => updateItem(it.key, { description: e.target.value })}
                        placeholder="What you delivered"
                        aria-label={`Line ${i + 1} description`}
                      />
                      {it.open ? (
                        <Textarea
                          rows={2}
                          value={it.details}
                          onChange={(e) => updateItem(it.key, { details: e.target.value })}
                          placeholder="Details — scope, dates, deliverables"
                          aria-label={`Line ${i + 1} details`}
                        />
                      ) : null}
                      <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                        {!it.open && (
                          <button
                            type="button"
                            onClick={() => updateItem(it.key, { open: true })}
                            className="min-h-8 text-[11.5px] text-sand transition-colors hover:text-cream pointer-coarse:min-h-9"
                          >
                            + Add details
                          </button>
                        )}
                        {catalogue.length > 0 && (
                          <CataloguePicker items={catalogue} currency={doc.currency} onPick={(entry) => fromCatalogue(it.key, entry)} />
                        )}
                      </div>
                      {/* Narrow: qty + rate, amount on its own line. Wide enough: one row of three. */}
                      <div className="grid grid-cols-[minmax(0,0.75fr)_minmax(0,1.25fr)] gap-2 @sm:grid-cols-[minmax(0,0.7fr)_minmax(0,1.1fr)_minmax(0,1.2fr)]">
                        <label className="min-w-0">
                          <span className="mb-1 block text-[9.5px] uppercase tracking-[0.16em] text-sand">Qty</span>
                          <Input
                            type="number"
                            inputMode="decimal"
                            min="0"
                            step="any"
                            value={it.quantity}
                            onChange={(e) => updateItem(it.key, { quantity: e.target.value })}
                            className="font-mono tabular-nums"
                          />
                        </label>
                        <label className="min-w-0">
                          <span className="mb-1 block text-[9.5px] uppercase tracking-[0.16em] text-sand">Rate</span>
                          <Input
                            type="number"
                            inputMode="decimal"
                            min="0"
                            step="0.01"
                            value={it.unit_price}
                            onChange={(e) => updateItem(it.key, { unit_price: e.target.value })}
                            placeholder="0.00"
                            className="font-mono tabular-nums"
                          />
                        </label>
                        <div className="col-span-2 flex min-w-0 items-baseline justify-between gap-3 @sm:col-span-1 @sm:block">
                          <span className="block text-[9.5px] uppercase tracking-[0.16em] text-sand @sm:mb-1">Amount</span>
                          <p className="truncate text-right font-mono text-[12.5px] text-cream tabular-nums @sm:border @sm:border-transparent @sm:py-2">
                            {docMoney(totals.lines[i] ?? 0, doc.currency)}
                          </p>
                        </div>
                      </div>
                      {(activeRates.length > 0 || it.taxes.length > 0) && (
                        <LineTaxes
                          taxes={it.taxes}
                          rates={activeRates}
                          onChange={(taxes) => updateItem(it.key, { taxes })}
                          label={`Line ${i + 1}`}
                        />
                      )}
                    </div>
                    <div className="flex shrink-0 flex-col gap-1">
                      <IconButton label={`Move line ${i + 1} up`} disabled={i === 0} onClick={() => moveItem(it.key, -1)}>
                        <Icon.up size={14} />
                      </IconButton>
                      <IconButton label={`Move line ${i + 1} down`} disabled={i === items.length - 1} onClick={() => moveItem(it.key, 1)}>
                        <Icon.down size={14} />
                      </IconButton>
                      <IconButton label={`Remove line ${i + 1}`} danger onClick={() => removeItem(it.key)}>
                        <Icon.trash size={14} />
                      </IconButton>
                    </div>
                  </div>
                </li>
              ))}
            </ol>
            <Button onClick={addItem} className="mt-3 min-h-9">
              <Icon.plus size={13} /> Add line
            </Button>
          </Panel>

          {/* Discount, tax, totals */}
          <Panel title="Discount & tax">
            <div className="grid grid-cols-1 gap-3 @md:grid-cols-2">
              <div>
                <span className={labelClass}>Discount</span>
                <div className="flex gap-1.5">
                  <div className="grid shrink-0 grid-cols-2 border border-cream/12">
                    {(["amount", "percent"] as const).map((t) => (
                      <button
                        key={t}
                        type="button"
                        aria-pressed={doc.discount_type === t}
                        onClick={() => set("discount_type", t)}
                        className={`min-h-9 px-3 text-[12px] transition-colors ${doc.discount_type === t ? "bg-terra/15 text-terra-bright" : "text-sand hover:text-cream"}`}
                      >
                        {t === "amount" ? doc.currency : "%"}
                      </button>
                    ))}
                  </div>
                  <Input
                    type="number"
                    inputMode="decimal"
                    min="0"
                    step="0.01"
                    value={doc.discount_value}
                    onChange={(e) => set("discount_value", e.target.value)}
                    placeholder="0"
                    className="font-mono tabular-nums"
                    aria-label="Discount"
                  />
                </div>
              </div>
              <div>
                <span className={labelClass}>Line prices</span>
                <div className="grid grid-cols-2 border border-cream/12" role="radiogroup" aria-label="Line prices">
                  {([false, true] as const).map((inc) => (
                    <button
                      key={String(inc)}
                      type="button"
                      role="radio"
                      aria-checked={doc.prices_include_tax === inc}
                      onClick={() => set("prices_include_tax", inc)}
                      className={`min-h-9 px-3 text-[12px] transition-colors ${doc.prices_include_tax === inc ? "bg-terra/15 text-terra-bright" : "text-sand hover:text-cream"}`}
                    >
                      {inc ? "Include tax" : "Before tax"}
                    </button>
                  ))}
                </div>
              </div>
            </div>
            {activeRates.length === 0 && totals.taxes.length === 0 && (
              <p className="mt-2.5 text-[11.5px] text-sand">
                No tax on this document.{" "}
                {viewer.admin ? "Add VAT, SSCL or other rates under Invoice settings › Taxes." : "An admin adds tax rates in Invoice settings."}
              </p>
            )}

            <dl className="mt-4 space-y-1.5 border-t border-cream/[0.08] pt-3 text-[12.5px]">
              <TotalRow term="Subtotal" value={docMoney(totals.subtotal, doc.currency)} />
              {totals.discount > 0 && <TotalRow term="Discount" value={`−${docMoney(totals.discount, doc.currency)}`} />}
              {doc.prices_include_tax && totals.tax > 0 && (
                <TotalRow term="Value before tax" value={docMoney(totals.net, doc.currency)} />
              )}
              {totals.taxes.map((t) => (
                <TotalRow
                  key={`${t.name}${t.rate}${t.compound}`}
                  term={`${t.name} ${t.rate}%${doc.prices_include_tax ? " (included)" : ""}`}
                  value={docMoney(t.amount, doc.currency)}
                />
              ))}
              <div className="flex items-baseline justify-between gap-3 border-t border-cream/[0.08] pt-2">
                <dt className="font-display text-[14px] text-cream">Total</dt>
                <dd className="font-mono text-[15px] text-terra-bright tabular-nums">{totalText}</dd>
              </div>
            </dl>
            {belowPaid && (
              <p className="mt-2 text-[12px] text-bad-300">
                The total can&apos;t drop below the {docMoney(paid, doc.currency)} already paid — remove a payment first.
              </p>
            )}
            {overCredit && creditFor && (
              <p className="mt-2 text-[12px] text-bad-300">
                That&apos;s more than the {docMoney(creditFor.room, creditFor.currency)} left to credit on {creditFor.number ?? "the invoice"}.
              </p>
            )}
            {foreign && num(doc.exchange_rate) > 0 && (
              <p className="mt-2 text-[11.5px] text-sand">
                ≈ {docMoney(Math.round(totals.total * num(doc.exchange_rate) * 100) / 100, "LKR")} at {num(doc.exchange_rate)}
              </p>
            )}
          </Panel>

          {/* Notes & payment */}
          <Panel title={credit ? "Notes" : "Notes & payment"} hint="Pre-filled from invoice settings. Edit for this document only.">
            <div className="space-y-3">
              <Field label="Payment details" hint="Bank and account — prints on a tinted panel.">
                <Textarea
                  rows={3}
                  value={doc.payment_details}
                  onChange={(e) => set("payment_details", e.target.value)}
                  className="font-mono"
                />
              </Field>
              <div className="grid grid-cols-1 gap-3 @md:grid-cols-2">
                <Field label="Notes">
                  <Textarea rows={3} value={doc.notes} onChange={(e) => set("notes", e.target.value)} />
                </Field>
                <Field label="Terms">
                  <Textarea rows={3} value={doc.terms} onChange={(e) => set("terms", e.target.value)} />
                </Field>
              </div>
            </div>
          </Panel>

          {/* Recurring */}
          {!quote && !credit && !invoice?.scheduled && (
            <Panel
              title={mode === "schedule" ? "Schedule" : "Make recurring"}
              hint={mode === "schedule" ? "How often it runs and what each run does." : "Retainers and subscriptions — this invoice is the first, the rest follow on schedule."}
              right={
                mode === "schedule" ? undefined : (
                  <label className="flex min-h-9 cursor-pointer items-center gap-2 text-[12px] text-cream-2">
                    <input
                      type="checkbox"
                      checked={recurring}
                      onChange={(e) => setRecurring(e.target.checked)}
                      className="h-4 w-4 accent-terra"
                    />
                    Repeat
                  </label>
                )
              }
            >
              {recurring ? (
                <div className="space-y-3">
                  <Field label="Schedule name">
                    <Input
                      value={sched.name}
                      onChange={(e) => setSched((s) => ({ ...s, name: e.target.value }))}
                      placeholder={scheduleName || "Kite Interiors · monthly support"}
                    />
                  </Field>
                  <div className="grid grid-cols-1 gap-3 @md:grid-cols-2">
                    <div className="grid grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)] gap-2">
                      <Field label="Repeats">
                        <Select
                          value={sched.frequency}
                          onChange={(e) => setSched((s) => ({ ...s, frequency: e.target.value as Frequency }))}
                        >
                          {FREQUENCIES.map((f) => (
                            <option key={f.value} value={f.value} className="bg-ink text-cream">
                              {f.label}
                            </option>
                          ))}
                        </Select>
                      </Field>
                      <Field label="Every">
                        <Input
                          type="number"
                          min="1"
                          step="1"
                          value={sched.interval_count}
                          onChange={(e) => setSched((s) => ({ ...s, interval_count: e.target.value }))}
                          className="font-mono tabular-nums"
                        />
                      </Field>
                    </div>
                    <Field
                      label="Next invoice on"
                      hint={nextTouched ? "Move it to a new day and later runs follow that day." : "One period after this invoice."}
                    >
                      <Input
                        type="date"
                        value={nextRun}
                        min={mode === "schedule" ? undefined : doc.issue_date}
                        onChange={(e) => {
                          setNextTouched(true);
                          setSched((s) => ({ ...s, next_run_on: e.target.value }));
                        }}
                      />
                    </Field>
                    <Field label="Ends on" hint="Optional.">
                      <Input
                        type="date"
                        value={sched.ends_on}
                        min={nextRun || undefined}
                        onChange={(e) => setSched((s) => ({ ...s, ends_on: e.target.value }))}
                      />
                    </Field>
                    <Field
                      label="Or after (invoices)"
                      hint={mode === "schedule" ? "Optional — stops after this many in all." : "Optional — stops after this many, this one included."}
                    >
                      <Input
                        type="number"
                        min="1"
                        step="1"
                        value={sched.max_occurrences}
                        onChange={(e) => setSched((s) => ({ ...s, max_occurrences: e.target.value }))}
                        className="font-mono tabular-nums"
                      />
                    </Field>
                  </div>
                  <div className="space-y-2.5 border-t border-cream/[0.08] pt-3">
                    <Checkbox
                      checked={sched.is_retainer}
                      onChange={(e) => setSched((s) => ({ ...s, is_retainer: e.target.checked }))}
                      label="This is a retainer"
                      hint="Counts towards MRR on the Recurring tab."
                    />
                    <Checkbox
                      checked={viewer.admin && sched.auto_issue}
                      disabled={!viewer.admin}
                      onChange={(e) => setSched((s) => ({ ...s, auto_issue: e.target.checked }))}
                      label="Issue automatically"
                      hint={
                        viewer.admin
                          ? "Numbered and issued on the run day. Off: a draft waits for review."
                          : schedule?.draft.auto_issue
                            ? "This schedule issues itself, which only an admin can change — saving switches it to drafts for review."
                            : "Only admins can auto-issue — your schedule creates drafts for review."
                      }
                    />
                    {mode === "schedule" && (
                      <Checkbox
                        checked={sched.active}
                        onChange={(e) => setSched((s) => ({ ...s, active: e.target.checked }))}
                        label="Active"
                        hint="Paused schedules generate nothing, and resuming skips the periods missed."
                      />
                    )}
                  </div>
                </div>
              ) : (
                <p className="text-[12px] text-sand">Off — this is a one-off {mode === "edit" ? "invoice" : "document"}.</p>
              )}
            </Panel>
          )}

          {/* Actions */}
          <div className="flex flex-wrap items-center justify-end gap-2 border-t border-cream/[0.08] pt-4">
            <Link href={cancelHref} className={`${linkButton.ghost} min-h-9`}>
              {mode === "create" ? "Cancel" : "Back"}
            </Link>
            {mode === "schedule" ? (
              <Button variant="primary" disabled={pending} onClick={() => save(false)} className="min-h-9">
                Save schedule
              </Button>
            ) : isDraft ? (
              <>
                <Button disabled={pending} onClick={() => save(false)} className="min-h-9">
                  {recurring && !quote && !credit ? "Save draft & schedule" : "Save draft"}
                </Button>
                <Button variant="primary" disabled={pending || overCredit} onClick={() => save(true)} className="min-h-9">
                  <Icon.send size={13} /> {quote ? "Save & mark sent" : credit ? "Save & apply" : "Save & issue"}
                </Button>
              </>
            ) : (
              <Button variant="primary" disabled={pending || belowPaid} onClick={() => save(false)} className="min-h-9">
                Save changes
              </Button>
            )}
          </div>

          {/* Below lg: total + preview, pinned to the bottom of the form */}
          <div
            className="sticky bottom-0 z-30 -mx-4 border-t border-cream/[0.10] bg-ink-2/95 px-4 pt-2.5 backdrop-blur-xl sm:-mx-6 sm:px-6 lg:hidden"
            style={{ paddingBottom: "max(0.625rem, var(--safe-b))" }}
          >
            <div className="flex items-center justify-between gap-3">
              <div className="min-w-0">
                <p className="text-[9.5px] uppercase tracking-[0.16em] text-sand">Total</p>
                <p className="truncate font-mono text-[14px] text-cream tabular-nums">{totalText}</p>
              </div>
              <Button onClick={() => setSheet(true)} className="min-h-10 shrink-0">
                <Icon.eye size={14} /> Preview
              </Button>
            </div>
          </div>
        </div>

        {/* lg+: the live paper */}
        <aside className="hidden min-w-0 lg:block" aria-label="Live preview">
          <div className="sticky top-6 max-h-[calc(100dvh-3rem)] overflow-y-auto scroll-thin" data-lenis-prevent>
            <div className="mb-2.5 flex items-center justify-between gap-3">
              <p className="eyebrow text-[9.5px]">Live preview</p>
              <p className="font-mono text-[11px] text-sand tabular-nums">{totalText}</p>
            </div>
            <ScaledSheet fitHeight offset={84}>
              <InvoiceDocument
                doc={shown}
                business={business}
                branding={branding}
                today={today}
                className="shadow-[0_40px_100px_-40px_var(--shadow-deep)]"
              />
            </ScaledSheet>
          </div>
        </aside>
      </div>

      {sheet &&
        createPortal(
          <div className="fixed inset-0 z-[110] flex flex-col bg-ink lg:hidden" role="dialog" aria-modal="true" aria-label="Preview">
            <header className="flex items-center justify-between gap-3 border-b border-cream/[0.08] bg-ink-2 px-4 py-2.5">
              <div className="min-w-0">
                <p className="eyebrow text-[9.5px]">Preview</p>
                <p className="truncate font-mono text-[13px] text-cream tabular-nums">{totalText}</p>
              </div>
              <button
                type="button"
                onClick={() => setSheet(false)}
                aria-label="Close preview"
                className="flex h-10 w-10 shrink-0 items-center justify-center border border-cream/12 text-cream-2 transition-colors hover:bg-cream/[0.06]"
              >
                <Icon.close size={16} />
              </button>
            </header>
            <div className="flex-1 overflow-y-auto p-4 scroll-thin" data-lenis-prevent data-modal>
              <ScaledSheet>
                <InvoiceDocument doc={shown} business={business} branding={branding} today={today} />
              </ScaledSheet>
            </div>
          </div>,
          document.body,
        )}
      {toast}
    </>
  );
}

function headHint(mode: Props["mode"], quote: boolean, credit: boolean) {
  if (mode === "schedule") return "The bill-to and lines every run copies.";
  if (credit) return "Numbered and applied to the invoice when you issue it. Trim the lines to credit part of it.";
  if (quote) return "Numbered when you mark it sent. Convert it to an invoice once accepted.";
  return "Numbered when you issue it. Drafts stay editable and unnumbered.";
}

function TotalRow({ term, value }: { term: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between gap-3 text-sand">
      <dt>{term}</dt>
      <dd className="font-mono text-cream-2 tabular-nums">{value}</dd>
    </div>
  );
}

function IconButton({
  label,
  onClick,
  disabled,
  danger,
  children,
}: {
  label: string;
  onClick: () => void;
  disabled?: boolean;
  danger?: boolean;
  children: ReactNode;
}) {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      disabled={disabled}
      onClick={onClick}
      className={`flex h-9 w-9 items-center justify-center border border-cream/[0.08] text-sand transition-colors disabled:opacity-30 ${danger ? "hover:border-bad-400/40 hover:text-bad-300" : "hover:border-cream/25 hover:text-cream"}`}
    >
      {children}
    </button>
  );
}
