"""Writes src/lib/admin/pdf/brand.generated.ts — the Flow State mark and an ink
wordmark as small PNG data: URLs for invoice PDFs.

The PDF renderer reads PNG/JPEG only (no WebP, no CSS masks), and the stock
wordmark is cream with a faint glow that would print as a grey haze: it's
recoloured to ink and the glow dropped, the same crop the paper uses.

    python3 scripts/gen-pdf-brand.py
"""
import base64
import io
from pathlib import Path

from PIL import Image

root = Path(__file__).resolve().parent.parent
brand = root / "public" / "brand"
INK = (28, 20, 16)


def png(img: Image.Image) -> str:
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


mark = Image.open(brand / "mark-256.png").convert("RGBA")
mark.thumbnail((160, 160), Image.LANCZOS)

wm = Image.open(brand / "wordmark.png").convert("RGBA").crop((28, 58, 857, 120))
alpha = wm.getchannel("A").point(lambda a: 0 if a < 90 else min(255, int((a - 90) * 255 / 165)))
ink = Image.new("RGBA", wm.size, INK + (0,))
ink.putalpha(alpha)
ink = ink.resize((ink.width * 2 // 3, ink.height * 2 // 3), Image.LANCZOS)

out = root / "src" / "lib" / "admin" / "pdf" / "brand.generated.ts"
out.write_text(
    "// GENERATED by scripts/gen-pdf-brand.py from public/brand — don't edit.\n"
    f'export const MARK_PNG = "{png(mark)}";\n'
    f'export const WORDMARK_INK_PNG = "{png(ink)}";\n'
    f"export const WORDMARK_SIZE = {{ width: {ink.width}, height: {ink.height} }};\n"
)
print(f"wrote {out.relative_to(root)} ({out.stat().st_size // 1024} KB)")
